---
- hosts: all
  become: true
  gather_facts: false
  roles:
    - role: python
    - role: users
  # vars:
  #   ansible_ssh_user: root

- hosts: all
  become: true
  gather_facts: false
  roles:
    - role: ping
