---
- name: Check if python installed
  ansible.builtin.raw: which python3
  args:
    executable: /bin/sh
  register: python
  changed_when: false
  failed_when: false

- name: Bootstrap python
  ansible.builtin.include_tasks: bootstrap_python.yaml
  when: python.stdout_lines[0] != '/usr/bin/python3'
