---
hostname: k3s-agent-0
users:
  - name: tt
    pubkey: ssh-rsa AAAAC....
    sudoer: true
k3s:
  exec: agent
  config:  # docs: https://docs.k3s.io/cli/agent
    token: <TOKEN HERE>
    server: https://<SERVER IP HERE>:6443
    node-label:
      - k3s.io/os=alpine
