---
hostname: k3s-agent-0
user:
  name: tt
  pubkey: ssh-rsa AAAAC....

k3s: # docs: https://docs.k3s.io/cli/agent
  exec: agent
  config:
    token: <TOKEN HERE>
    server: https://<SERVER IP HERE>:6443
    node-label:
      - k3s.io/os=alpine
