---
hostname: k3s-server-0
user:
  name: tt
  pubfile: $HOME/.ssh/id_ed25519.pub

k3s: # docs: https://docs.k3s.io/cli/server
  exec: server
  config:
    cluster-init: true
    node-labels:
      - k3s.io/os=alpine
