---
- name: Check connection
  ansible.builtin.wait_for_connection:
    timeout: 30
  ignore_errors: true
  register: connection_status

- name: Create users and disable root
  ansible.builtin.include_tasks: create_users.yaml
  when: |
    connection_status.failed and
    'Permission denied' in connection_status.msg
