---
hostname: sauron

users:
  - name: tt
    pubkey: ssh-ed25519 AAAAC3N...
    sudoer: true

# additional packages to install
packages:
  # below are preprequisites for longhorn
  - name: bash
  - name: jq
  - name: open-iscsi
    service: iscsid # this service will be started after iscsid is installed
  - name: nfs-utils

# drives to mount
mounts:
  # writable partition to keep k3s data on
  # Alpine runs in memory and these paths need to live on disk
  - label: kubelet-sauron
    path: /mnt/k3s-persisted-state
  - label: k3s-data-sauron
    path: /var/lib/longhorn
    flags: --make-rshared

# mount -o bind <source> <target>
binds:
  # bind mount k3s folders into the writable partition
  - source: /mnt/k3s-persisted-state/var/lib/rancher
    target: /var/lib/rancher
  - source: /mnt/k3s-persisted-state/var/lib/kubelet
    target: /var/lib/kubelet
  - source: /mnt/k3s-persisted-state/etc/rancher
    target: /etc/rancher
  - source: /mnt/k3s-persisted-state/run/k3s
    target: /run/k3s

k3s:
  exec: server
  config:  # docs: https://docs.k3s.io/cli/server
    cluster-init: true
    node-labels:
      - k3s.io/os=alpine
